clone:
  disable: 'true'
kind: pipeline
name: gin-proc
steps:
- commands:
  - eval $(ssh-agent -s)
  - mkdir -p /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
  - mkdir -p /etc/ssh
  - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  - ssh-add /root/.ssh/id_rsa
  - git clone "$DRONE_GIT_SSH_URL"
  - cd "$DRONE_REPO_NAME"/
  - pip3 install -r requirements.txt
  - git annex init ""$DRONE_REPO_NAME"-drone-annexe"
  - git annex sync --content
  - snakemake
  - echo ".snakemake/" > .gitignore
  environment:
  - SSH_KEY:
      from_secret: DRONE_PRIVATE_SSH_KEY
  image: falconshock/gin-proc:micro-test
  name: execute
  volumes:
  - name: repo
    path: /repo
- image: plugins/slack
  name: notification
  settings:
    webhook: https://hooks.slack.com/services/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
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
volumes:
- host:
    path: /gin-proc/cache
  name: cache
- host:
    path: /gin-proc/repo
  name: repo
